import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Articles from '../data'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faPencil, faPencilSquare } from '@fortawesome/free-solid-svg-icons'
import Link from 'next/link'

import { useSession, signIn, signOut } from 'next-auth/react'
import { useState } from 'react'

const Home: NextPage = () => {
  const { data: session, status } = useSession()
  const loading = status === 'loading'
  const [category, setCategory] = useState('latest')

  if (loading) {
    return <h1>Loading... Please Wait!</h1>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Robo-Reporter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </Head>

      <div className='text-xs max-w-xs'>
        <Link href={"/articles/new"}>
          <p className='text-xs'><FontAwesomeIcon icon={faPencilSquare} size='sm' className='text-5xl dark:text-white social-link hover:shadow-md'/></p>
        </Link>
      </div>

      {/* <form action="/articles/edit/">
        <label htmlFor="article-id">Article ID: </label>
        <input type="number" name="id" id="article-id" className='max-w-xs rounded-md'/>
      </form> */}

      {
        status == 'authenticated' ? 
        <span>
          <div className='max-w-lg text-sm'>
            <Link href={`/articles/edit/2`}>
              <FontAwesomeIcon icon={faPencil} size='lg' className='dark:text-white text-xs hover:text-orange-400'/>
            </Link>
          </div>
        </span>
        : 
        <div />
      }

      <br />
      <br />

      <main className={styles.main}>
        {Articles.map((article, idx) => {
          return article.posted && <div key={idx} className={`${styles.card} max-h-80 overflow-hidden max-w-lg`} onClick={() => {
            window.open(`/articles/${article.category.toLowerCase()}/${article.id}`, "_empty")
          }}>
            <Image src={article.coverImage} width="1000" height="500" alt="cover image for article" priority />
            
            <span className='text-orange-500 uppercase'>{article.category} · {new Date(article.createdAt).toLocaleDateString()}</span>
            <h1 className='text-lg font-bold dark:text-white'>{article.title}</h1>
            
            <p className='dark:text-white text-xs'>{article.content.slice(0, 120)}</p>
          </div>
        })}
      </main>
    </div>
  )
}

export default Home
